### PR TITLE
added feature for online player required when making backup

### PR DESCRIPTION
**Pull request by kafuuchino-desu**
@Fallen-Breath uwu

### CODE REVIEW

**Comment by Fallen-Breath** [comment]
Seems like your commit doesn't contain related changes. Wrong file path? Uncommited files?

**Comment by kafuuchino-desu** [comment]
> Seems like your commit doesn't contain related changes. Wrong file path? Uncommited files?

Line 90-94, and 101-114, probably it's me using web upload and it says I modified the whole file

**Comment by Fallen-Breath** [comment]
Wrong file path of the `entry.py` then

**Comment by Fallen-Breath** [comment]
Also I suggest to make the default value of `require_online_players` be `false`, so no un-noticed behavior change

**Comment by kafuuchino-desu** [comment]
oh crap, didn't noticed I screw this up. I'll delete this branch and close this pull request, then use a clean branch to open another pull request💀💀💀

**Pull request closed without merging**
